### ISSUE TITLE
Sorts and custom soundfonts not loading

### ISSUE THREAD

**Issue by nerdgh0st** [Gaming32/ArrayV#84]
the "0 Sorts" bug returns... including the bug where it can't load other soundfonts!
![IyymxWYF0y](https://user-images.githubusercontent.com/68407522/162653194-d93f4202-f865-458e-9b0b-00b911c174bf.png)
![javaw_70ro6ZW7QF](https://user-images.githubusercontent.com/68407522/162653198-45cad551-b041-46f4-b846-bd40025f2dea.png)
![javaw_sLv2LQAUzx](https://user-images.githubusercontent.com/68407522/162653207-20e104eb-087b-4730-bd81-19b39ea793ad.png)

**Comment by EmeraldBlock** [comment]
could you explain how to recreate it / what you're running on?

**Comment by Gaming32** [comment]
Please also rename the issue to something more descriptive.

**Comment by Gaming32** [comment]
This appears to be an issue with loading soundfonts from the JAR (https://stackoverflow.com/questions/38339542/java-io-ioexception-mark-reset-not-supported).

**Comment by Gaming32** [comment]
It does indeed fail for me on Java 8.
