### ISSUE TITLE
ArrayV refuses to load custom soundbanks

### ISSUE THREAD

**Issue by VyaCHACHsel** [Gaming32/ArrayV#88]
### Errors
ArrayV at the start it shows this:
![image](https://user-images.githubusercontent.com/60910714/189485440-da9917e8-1767-4ef5-92d2-09163ea3ae45.png)

After that, it works just fine (and even plays the sound), but trying to choose a soundbank shows me this:
![image](https://user-images.githubusercontent.com/60910714/189485508-1526c092-0156-4f31-91d4-2b2981071690.png)

### What I did
1. Open the program (error box 1)
2. In the window with sound settings, press "Choose soundbank..."
3. In the appeared window choose any *.sf2 file.
4. Get an error (error box 2)

### Computer specs that can save your time
**OS:** Microsoft Windows 11, 21H2
**CPU:** Intel Core i3-1005G1 @ 1.20 GHz
**GPU:** None (Intel UHD Graphics)
**RAM:** 4 GB (3,81 GB available, other dedicated to UHD Graphics I suppose)
**Type:** Laptop

**Comment by Gaming32** [comment]
This is fixed, and actually has been for a while. Just forgot to close the issue.
