### ISSUE TITLE
how to open

### ISSUE THREAD

**Issue by rylid-umil** [Gaming32/ArrayV#91]
what does it mean to run ./run in shell or ./mvnw clean verify? the run.bet file says something about java-home

**Comment by Gaming32** [comment]
Just download the latest build from [nightly.link](https://nightly.link/Gaming32/ArrayV/workflows/maven/main/standalone-jar.zip).

**Comment by Gaming32** [comment]
Also the place to ask for support is [the Discord](https://discord.gg/thestudio), not GitHub Issues.
